trigger: none

pool:
  vmImage: windows-latest

variables:
- template: vars/global.yml

stages:
- template: templates/stage/sharedinfra-env-stage.yml
  parameters:
    environmentName: dev
    mainBicep: cleansample-shared-infra

# - template: templates/stage/sharedinfra-env-stage.yml
#   parameters:
#     environmentName: tst
#     mainBicep: cleansample-shared-infra

# - template: templates/stage/sharedinfra-env-stage.yml
#   parameters:
#     environmentName: prd
#     mainBicep: cleansample-shared-infra
