parameters:
- name: buildProjectFile
  type: string
- name: testProjectFiles 
  type: string 
- name: env
  type: object
  default:
    dummy: "dummy"

jobs:
- job: Build
  displayName: Build
  steps:
  - template: ../task/dotnet-restore-config-task.yml
  - template: ../task/dotnet-build-projects-task.yml
    parameters:
      projects: ${{ parameters.buildProjectFile }}
  - template: ../task/dotnet-test-projects-task.yml 
    parameters:
      projects: ${{ parameters.testProjectFiles }}
      env: ${{ parameters.env }}
