parameters:
- name: azureSubscription
  type: string
- name: resourceGroup
  type: string
- name: functionAppName
  type: string
- name: keyVaultName
  type: string
- name: storageAccountSku
  type: string
  default: Standard_LRS
- name: location
  type: string
  default: westeurope
- name: osType
  type: string
  values: 
    - Linux
    - Windows
  default: Windows
- name: corsAllowedOrigins
  type: object
  default: []
- name: enableCors 
  type: string 
  default: false
- name: useStagingSlot
  type: string
  default: false 

jobs:
- job: CreateFunctionApp
  displayName: Create function app
  steps:
  - template: ../task/resourcegroup-create-task.yml
    parameters:
      azureSubscription: ${{parameters.azureSubscription}}
      location: ${{parameters.location}}
      resourceGroup: ${{parameters.resourceGroup}}
  - template: ../task/keyvault-create-task.yml
    parameters:
      azureSubscription: ${{parameters.azureSubscription}}
      resourceGroup: ${{parameters.resourceGroup}}
      keyVaultName: ${{parameters.keyVaultName}}
  - template: ../task/storage-account-create-task.yml
    parameters:
      azureSubscription: ${{parameters.azureSubscription}}
      resourceGroup: ${{parameters.resourceGroup}}
      storageAccountName: ${{parameters.functionAppName}}sa
      location: ${{parameters.location}}
      sku: ${{parameters.storageAccountSku}}
  - template: ../task/functionapp-create-task.yml
    parameters:
      azureSubscription: ${{parameters.azureSubscription}}
      resourceGroup: ${{parameters.resourceGroup}}
      functionAppName: ${{parameters.functionAppName}}
      storageAccountName: ${{parameters.functionAppName}}sa
      location: ${{parameters.location}}
      osType: ${{parameters.osType}}
  - template: ../task/keyvault-access-policies-functionapp-task.yml
    parameters:
      azureSubscription: ${{parameters.azureSubscription}}
      resourceGroup: ${{parameters.resourceGroup}}
      functionAppName: ${{parameters.functionAppName}}
      keyVaultName: ${{parameters.keyVaultName}}
  - template: ../task/functionapp-cors-add-allowed-origins-task.yml
    parameters:
      azureSubscription: ${{parameters.azureSubscription}}
      resourceGroup: ${{parameters.resourceGroup}}
      functionAppName: ${{parameters.functionAppName}}
      corsAllowedOrigins: ${{parameters.corsAllowedOrigins}}
  - template: ../task/functionapp-cors-set-enable-task.yml
    parameters:
      azureSubscription: ${{parameters.azureSubscription}}
      resourceGroup: ${{parameters.resourceGroup}}
      functionAppName: ${{parameters.functionAppName}}
      enableCors: ${{parameters.enableCors}}
