parameters:
- name: buildProjectFile
  type: string
- name: publishProjectFiles
  type: string
- name: projectName 
  type: string 

jobs:
- job: Publish
  displayName: Publish
  steps:
  - template: ../task/dotnet-restore-config-task.yml
  - template: ../task/dotnet-build-projects-task.yml
    parameters:
      projects: ${{ parameters.buildProjectFile }}
  - template: ../task/dotnet-publish-projects-task.yml
    parameters:
      projects: ${{ parameters.publishProjectFiles }}
  - template: ../task/publish-pipeline-artifact-task.yml    
    parameters:
      targetPath: $(Build.ArtifactStagingDirectory)/${{ parameters.projectName }}