parameters:
- name: buildProjectFile
  type: string
- name: publishProjectFiles
  type: string
- name: projectFileName 
  type: string 

jobs:
- job: Publish
  displayName: Publish
  steps:
  - template: ../task/dotnet-restore-config-task.yml
  - template: ../task/dotnet-build-projects-task.yml
    parameters:
      projects: ${{ parameters.buildProjectFile }}
  - template: ../task/dotnet-publish-projects-task.yml
    parameters:
      projects: ${{ parameters.publishProjectFiles }}
  - task: ArchiveFiles@2
    displayName: "Archive project files"
    inputs:
      rootFolderOrFile: $(Build.ArtifactStagingDirectory)/${{ parameters.projectFileName }}
      includeRootFolder: false
      archiveFile: $(Build.ArtifactStagingDirectory)/${{ parameters.projectFileName }}.zip
  - template: ../task/publish-pipeline-artifact-task.yml    
    parameters:
      targetPath: $(Build.ArtifactStagingDirectory)/${{ parameters.projectFileName }}