trigger: none

pool:
  vmImage: windows-latest

variables:
- name: mainBicep
  value: cleansample-shared-infra.bicep
- template: /vars/global.yml

stages:
- template: /templates/stage/shared-infra-stage.yml
  parameters:
    environmentName: dev
    mainBicep: $(mainBicep)

- template: /templates/stage/shared-infra-stage.yml
  parameters:
    environmentName: tst
    mainBicep: $(mainBicep)

- template: /templates/stage/shared-infra-stage.yml
  parameters:
    environmentName: prd
    mainBicep: $(mainBicep)
