parameters:
- name: env
  type: object
  default:
    dummy: "dummy"

stages:
- stage: Build
  displayName: Build
  jobs:
  - template: ../job/build-job.yml
    parameters:
      buildProjectFile: $(buildProjectFile)
      testProjectFiles: $(testProjectFiles)
      env: ${{ parameters.env }}
  - template: ../job/publish-job.yml
    parameters:
      buildProjectFile: $(buildProjectFile)
      publishProjectFiles: $(publishProjectFiles)
      projectFileName: $(projectName)
