parameters:
- name: environmentName
  type: string
- name: mainBicep
  type: string

stages:
- stage: ${{ parameters.environmentName }}
  variables:
    resourcesNameBase: cleansample-${{ parameters.environmentName }}-shared
  jobs:
  - deployment: ${{ parameters.environmentName }}InfraDeployment
    environment: cleansample-${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'Create Shared Resources'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                az deployment sub create `
                  --template-file $(Build.SourcesDirectory)\main\${{ parameters.mainBicep }}.bicep `
                  --parameters $(Build.SourcesDirectory)\main\${{ parameters.mainBicep }}.bicepparam
            env:
              resourcesNameBase: $(resourcesNameBase)
